function [features, best_accuracy] = nearest_neighbor()
fprintf('Welcome to Salman Bana Feature Selection Algorithm. \n')
prompt = 'Type in the name of the file to test: ';
str = input(prompt, 's');
data = importdata(str);
idx = randperm(size(data, 1));
shuffled_data = data(idx, :);
X = shuffled_data(:, 2:end); Y = shuffled_data(:, 1);
prompt = ['Type the number of the algorithm you want to run. \n' ...
    '1) Forward Selection \n2) Backward Elimination \n' ...
    '3) Salman Special Algorithm \n'];
alg_num = input(prompt);
stuff_to_say = ['This dataset has %d features' ...
    '(not including the class attribute), with %d instances. \n' ...
    'Please wait while I normalize the data…   Done! \n' ...
    'Running nearest neighbor with all %d features,' ...
    'using “leaving-one-out” evaluation, I get an accuracy of %f \n'];
fprintf(stuff_to_say, size(X, 2), size(X, 1), size(X, 2), ...
    cross_validation(X, Y));
[features, best_accuracy] = search_algorithm(X, Y, alg_num);
end